### ISSUE TITLE
AssertionError: different bucketing for key/values for causal reordering not supported yet

### ISSUE THREAD

**Issue by timsoraro** [lucidrains/sinkhorn-transformer#11]
```python
len self.examples: 0
Traceback (most recent call last):
  File "train.py", line 255, in <module>
    n_local_attn_heads = 4
  File "/home/deepspeed/.local/lib/python3.6/site-packages/sinkhorn_transformer/sinkhorn_transformer.py", line 760, in __init__
    self.sinkhorn_transformer = SinkhornTransformer(dim, depth, max_seq_len = max_seq_len, causal = causal, heads = heads, bucket_size = bucket_size, kv_bucket_size = kv_bucket_size, context_bucket_size = context_bucket_size, non_permutative = non_permutative, sinkhorn_iter = sinkhorn_iter, n_sortcut = n_sortcut, temperature = temperature, reversible = reversible, ff_chunks = ff_chunks, ff_dropout = ff_dropout, attn_dropout = attn_dropout, attn_layer_dropout = attn_layer_dropout, layer_dropout = layer_dropout, weight_tie = weight_tie, ff_glu = ff_glu, use_simple_sort_net = use_simple_sort_net, receives_context = receives_context, context_n_sortcut = context_n_sortcut, n_local_attn_heads = n_local_attn_heads)
  File "/home/deepspeed/.local/lib/python3.6/site-packages/sinkhorn_transformer/sinkhorn_transformer.py", line 713, in __init__
    PreNorm(nn.LayerNorm, dim, get_attn()),
  File "/home/deepspeed/.local/lib/python3.6/site-packages/sinkhorn_transformer/sinkhorn_transformer.py", line 702, in <lambda>
    get_attn = lambda: SinkhornSelfAttention(dim, bucket_size, max_seq_len, causal = causal, heads = heads, kv_bucket_size = kv_bucket_size, non_permutative = non_permutative, sinkhorn_iter = sinkhorn_iter, n_sortcut = n_sortcut, temperature = temperature, attn_dropout = attn_dropout, dropout = attn_layer_dropout, use_simple_sort_net = use_simple_sort_net, n_local_attn_heads = n_local_attn_heads)
  File "/home/deepspeed/.local/lib/python3.6/site-packages/sinkhorn_transformer/sinkhorn_transformer.py", line 652, in __init__
    attn = SinkhornCausalAttention(bucket_size, dim, dim_heads, sink_heads, max_seq_len, dropout = attn_dropout, kv_bucket_size = kv_bucket_size, use_simple_sort_net = use_simple_sort_net)
  File "/home/deepspeed/.local/lib/python3.6/site-packages/sinkhorn_transformer/sinkhorn_transformer.py", line 525, in __init__
    assert kv_bucket_size is None, 'different bucketing for key/values for causal reordering not supported yet'
AssertionError: different bucketing for key/values for causal reordering not supported yet

```

**Comment by timsoraro** [comment]
I've tried setting `kv_bucket_size=128,` but it didn't work.

**Comment by lucidrains** [comment]
@timsoraro I'm still working on that, almost done! the causal masking is tricky..

**Comment by lucidrains** [comment]
@timsoraro if you keep it the same as `bucket_size`, it should work fine!

Edit - oh, I had a bug :( https://github.com/lucidrains/sinkhorn-transformer/commit/baa576355e9b7fbc5aec62578a39c56cba8a67bf sorry about that

**Comment by timsoraro** [comment]
Gone 👍
