### ISSUE TITLE
AttributeError: 'ProjectInOut' object has no attribute 'pad_to_bucket_size'

### ISSUE THREAD

**Issue by timsoraro** [lucidrains/sinkhorn-transformer#12]
Hah, doing QA. I get this error now:

```python
Traceback (most recent call last):
  File "train.py", line 260, in <module>
    model = AutoregressiveWrapper(model, ignore_index=PAD_ID, pad_value=PAD_ID)
  File "/home/deepspeed/.local/lib/python3.6/site-packages/sinkhorn_transformer/autoregressive_wrapper.py", line 34, in __init__
    self.net = Autopadder(net, pad_left = pad_left)
  File "/home/deepspeed/.local/lib/python3.6/site-packages/sinkhorn_transformer/autopadder.py", line 28, in __init__
    self.bucket_size = sinkhorn.pad_to_bucket_size
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 591, in __getattr__
    type(self).__name__, name))
AttributeError: 'ProjectInOut' object has no attribute 'pad_to_bucket_size'
```

**Comment by lucidrains** [comment]
@timsoraro i'm embarrassed lol https://github.com/lucidrains/sinkhorn-transformer/commit/5f79052acd2f4ffd411a6375b72c45ebd74ef5ab hopefully last one

**Comment by timsoraro** [comment]
I wonder why I get this error now:

```python
Traceback (most recent call last):
  File "train.py", line 266, in <module>
    model_engine, optimizer, trainloader, _ = deepspeed.initialize(args=cmd_args, model=model, model_parameters=model.parameters(),  training_data=train_dataset)
  File "/usr/local/lib/python3.6/dist-packages/deepspeed/__init__.py", line 96, in initialize
    collate_fn=collate_fn)
  File "/usr/local/lib/python3.6/dist-packages/deepspeed/pt/deepspeed_light.py", line 136, in __init__
    self._configure_with_arguments(args, mpu)
  File "/usr/local/lib/python3.6/dist-packages/deepspeed/pt/deepspeed_light.py", line 377, in _configure_with_arguments
    self._config = DeepSpeedConfig(args.deepspeed_config, mpu)
  File "/usr/local/lib/python3.6/dist-packages/deepspeed/pt/deepspeed_config.py", line 236, in __init__
    self._param_dict = json.load(open(json_file, 'r'))
  File "/usr/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 3 column 37 (char 65)
```

And using the code from the deepspeed example (non-deepspeed seems to work):

```python
Traceback (most recent call last):
  File "train_deepspeed.py", line 96, in <module>
    model_engine, optimizer, trainloader, _ = deepspeed.initialize(args=cmd_args, model=model, model_parameters=model.parameters(),  training_data=train_dataset)
  File "/usr/local/lib/python3.6/dist-packages/deepspeed/__init__.py", line 96, in initialize
    collate_fn=collate_fn)
  File "/usr/local/lib/python3.6/dist-packages/deepspeed/pt/deepspeed_light.py", line 129, in __init__
    dist.init_process_group(backend=self.dist_backend)
  File "/usr/local/lib/python3.6/dist-packages/torch/distributed/distributed_c10d.py", line 406, in init_process_group
    store, rank, world_size = next(rendezvous(url))
  File "/usr/local/lib/python3.6/dist-packages/torch/distributed/rendezvous.py", line 119, in _env_rendezvous_handler
    raise _env_error("RANK")
ValueError: Error initializing torch.distributed using env:// rendezvous: environment variable RANK expected, but not set
```

**Comment by lucidrains** [comment]
@timsoraro hmm i'm not too sure, it looks like a deepspeed related error

could you try the same `ds_config.json` settings you did for reformer?

**Comment by timsoraro** [comment]
Sorry, a problem with my `ds_config.json`! Left one parameter blank. Closing this, thanks :)
