### ISSUE TITLE
RuntimeError: range cannot be used as a value

### ISSUE THREAD

**Issue by timsoraro** [lucidrains/sinkhorn-transformer#9]
Thanks for this repo, I get it's rough at the start. I get this error when trying to train the wikitext example:
```python
Traceback (most recent call last):
  File "train.py", line 1, in <module>
    from sinkhorn_transformer import SinkhornTransformerLM
  File "/home/deepspeed/.local/lib/python3.6/site-packages/sinkhorn_transformer/__init__.py", line 1, in <module>
    from sinkhorn_transformer.sinkhorn_transformer import SinkhornTransformer, SinkhornTransformerLM, SinkhornSelfAttention
  File "/home/deepspeed/.local/lib/python3.6/site-packages/sinkhorn_transformer/sinkhorn_transformer.py", line 128, in <module>
    @torch.jit.script
  File "/usr/local/lib/python3.6/dist-packages/torch/jit/__init__.py", line 1181, in script
    return _compile_function(fn=obj, qualified_name=qualified_name, _frames_up=_frames_up + 1, _rcb=_rcb)
  File "/usr/local/lib/python3.6/dist-packages/torch/jit/__init__.py", line 1077, in _compile_function
    script_fn = torch._C._jit_script_compile(qualified_name, ast, _rcb, get_default_args(fn))
RuntimeError: 
range cannot be used as a value:
at /home/deepspeed/.local/lib/python3.6/site-packages/sinkhorn_transformer/sinkhorn_transformer.py:133:60
@torch.jit.script
def tensor_iterator_wrapper(padded_x, t, forward, backward):
    int_t = int(t.item())
    int_forward = int(forward.item())
    int_backward = int(backward.item())
    return [padded_x[:, ind:(ind + int_t), ...] for ind in range(int_forward + int_backward + 1)]
                                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
```

I get the same error with/without deepspeed. The error above is without.

**Comment by lucidrains** [comment]
@timsoraro oops, put out a quick fix for now, my bad!

https://github.com/lucidrains/sinkhorn-transformer/commit/3d2c3dba3c0365c5958c86b13a4491a1efaf3ce3

**Comment by timsoraro** [comment]
:)
